// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5MxBizS9_1u_0aASC61Z_8dE8FdQ8RQQ',
    appId: '1:690425428957:web:1305762b40ec3b4b0c1434',
    messagingSenderId: '690425428957',
    projectId: 'fatec-manha-loja-cafe-2022',
    authDomain: 'fatec-manha-loja-cafe-2022.firebaseapp.com',
    storageBucket: 'fatec-manha-loja-cafe-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAltWhyNRFpdcqgXiOsQ9RJu20FHpe_mi8',
    appId: '1:690425428957:android:6a61434885c7209e0c1434',
    messagingSenderId: '690425428957',
    projectId: 'fatec-manha-loja-cafe-2022',
    storageBucket: 'fatec-manha-loja-cafe-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM2y4tICFyfa9tdGfm7t7n8hLUclk8lFk',
    appId: '1:690425428957:ios:222d0282e5b05be00c1434',
    messagingSenderId: '690425428957',
    projectId: 'fatec-manha-loja-cafe-2022',
    storageBucket: 'fatec-manha-loja-cafe-2022.appspot.com',
    iosClientId: '690425428957-9j6lk54jpjusvbv1ch9gkr4ut59o8bsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app07LojaCafe',
  );
}
